---
- name: Install Xorg, Openbox, Chromium, xserver-xorg-legacy and utilities
  ansible.builtin.apt:
    name:
      - xserver-xorg
      - x11-xserver-utils
      - xinit
      - openbox
      - chromium-browser
      - xserver-xorg-legacy
    state: present
    update_cache: yes

- name: Configure Xwrapper to allow any user to start X
  ansible.builtin.copy:
    dest: /etc/X11/Xwrapper.config
    content: |
      allowed_users=anybody
      needs_root_rights=yes
    owner: root
    group: root
    mode: '0644'

- name: Create .xinitrc for dakboard user to start openbox and chromium kiosk
  ansible.builtin.copy:
    dest: /home/dakboard/.xinitrc
    content: |
      #!/bin/bash
      exec >> /home/dakboard/x11-kiosk.log 2>&1
      echo "Starting X session at \$(date)"
      xset -dpms
      xset s off
      xset s noblank
      openbox-session &
      chromium-browser --noerrdialogs --kiosk https://dakboard.com/display/uuid/684e4b30-13c2a8-8eef-71fbcdfe --incognito --disable-translate --disable-infobars --check-for-update-interval=1 &
      wait
      echo "X session ended at \$(date)"
    owner: dakboard
    group: dakboard
    mode: '0755'

- name: Deploy fixed systemd service for X11 kiosk session
  ansible.builtin.copy:
    dest: /etc/systemd/system/x11-kiosk.service
    content: |
      [Unit]
      Description=X11 Kiosk Session on tty1
      After=network.target getty@tty1.service
      Requires=getty@tty1.service

      [Service]
      User=dakboard
      Environment=DISPLAY=:0
      Environment=XDG_RUNTIME_DIR=/run/user/1001
      ExecStartPre=/bin/rm -f /tmp/.X0-lock
      ExecStart=/usr/bin/startx /home/dakboard/.xinitrc -- vt1
      Restart=always
      RestartSec=5
      StandardOutput=syslog
      StandardError=syslog
      SyslogIdentifier=x11-kiosk

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  become: true

- name: Enable and start x11-kiosk service
  ansible.builtin.systemd:
    name: x11-kiosk.service
    enabled: yes
    state: restarted
  become: true

