---
# Modular Ansible site playbook
# Use feature flags in group_vars/all.yml to control what gets deployed

- import_playbook: playbooks/01_base_setup.yml

- import_playbook: playbooks/02_kiosk_touchscreen.yml
  when: enable_kiosk | default(false)

- import_playbook: playbooks/03_dakboard.yml
  when: enable_dakboard | default(false)

- import_playbook: playbooks/04_prepare_containers.yml
  when: enable_containers | default(false)

- import_playbook: playbooks/05_containers_homeassistant.yml
  when: enable_homeassistant | default(false)

- import_playbook: playbooks/06_traefik_ingress.yml
  when: enable_traefik | default(false)

- import_playbook: playbooks/07_k3s_control_plane.yml
  when: enable_k3s | default(false)

- import_playbook: playbooks/08_k3s_worker_nodes.yml
  when: enable_k3s | default(false) and groups['workers'] is defined and groups['workers'] | length > 0

- import_playbook: playbooks/09_homebridge.yml
  when: enable_homebridge | default(false)

- import_playbook: playbooks/10_mqtt.yml
  when: enable_mqtt | default(false)

- import_playbook: playbooks/11_nodered.yml
  when: enable_nodered | default(false)

- import_playbook: playbooks/12_postgresql.yml
  when: enable_postgresql | default(false)

- import_playbook: playbooks/12_pxe_server.yml
  when: enable_pxe_server | default(false)

- import_playbook: playbooks/13_ai_stack.yml
  when: enable_ai_stack | default(false)