---
- name: Install Mosquitto MQTT broker
  apt:
    name:
      - mosquitto
      - mosquitto-clients
    state: present
    update_cache: yes
  become: yes

- name: Create mosquitto configuration directory
  file:
    path: /etc/mosquitto/conf.d
    state: directory
    owner: mosquitto
    group: mosquitto
    mode: '0755'
  become: yes

- name: Configure mosquitto broker
  template:
    src: mosquitto.conf.j2
    dest: /etc/mosquitto/conf.d/custom.conf
    owner: mosquitto
    group: mosquitto
    mode: '0644'
  become: yes
  notify: restart mosquitto

- name: Create mosquitto password file if authentication is enabled
  template:
    src: passwd.j2
    dest: /etc/mosquitto/passwd
    owner: mosquitto
    group: mosquitto
    mode: '0600'
  become: yes
  when: mqtt_auth_enabled | default(false)
  notify: restart mosquitto

- name: Generate password hash for mosquitto
  shell: mosquitto_passwd -c /etc/mosquitto/passwd {{ mqtt_username }}
  args:
    stdin: "{{ mqtt_password }}"
  become: yes
  when: mqtt_auth_enabled | default(false)
  notify: restart mosquitto

- name: Enable and start mosquitto service
  systemd:
    name: mosquitto
    enabled: yes
    state: started
  become: yes

- name: Open MQTT port in firewall
  ufw:
    rule: allow
    port: '1883'
    proto: tcp
  become: yes
  when: enable_firewall | default(true)