---
- name: Create getty override directory for tty1
  ansible.builtin.file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory
    mode: '0755'

- name: Configure autologin on tty1 as dakboard
  ansible.builtin.copy:
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=-/sbin/agetty --autologin dakboard --noclear %I $TERM
    mode: '0644'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart getty@tty1 service to apply autologin
  ansible.builtin.systemd:
    name: getty@tty1.service
    state: restarted
    enabled: true
