apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: default
type: Opaque
data:
  # username: hauser (base64 encoded)
  username: aGF1c2Vy
  # password: hasecret (base64 encoded)
  password: aGFzZWNyZXQ=
  # database: homeassistant (base64 encoded)
  database: aG9tZWFzc2lzdGFudA==