---
- name: Get k3s token from control plane
  set_fact:
    k3s_token: "{{ hostvars[groups['control'][0]]['k3s_token'] }}"

- name: Install k3s agent
  shell: |
    curl -sfL https://get.k3s.io | K3S_URL="https://{{ hostvars[groups['control'][0]]['ansible_host'] }}:6443" K3S_TOKEN="{{ k3s_token }}" sh -
  args:
    creates: /etc/systemd/system/k3s-agent.service
