---
- name: Install k3s agent
  shell: |
    curl -sfL https://get.k3s.io | K3S_URL="https://{{ k3s_control_ip }}:6443" K3S_TOKEN="{{ k3s_token }}" sh -
  args:
    creates: /etc/systemd/system/k3s-agent.service
