---
- name: Install Cockpit and Podman
  hosts: all
  become: true
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Cockpit
      apt:
        name: cockpit
        state: present

    - name: Install Podman
      apt:
        name: podman
        state: present

    - name: Ensure cockpit service is enabled and started
      systemd:
        name: cockpit
        enabled: yes
        state: started

    - name: Ensure podman service is enabled and started
      systemd:
        name: podman
        enabled: yes
        state: started
