---
- name: Install MongoDB and UniFi Network Controller
  hosts: all
  become: true
  tasks:

    # Step 1: Install required packages for MongoDB (gnupg, curl)
    - name: Install required packages for MongoDB
      apt:
        name:
          - gnupg
          - curl
        state: present
        update_cache: yes

    # Step 2: Add MongoDB GPG key
    - name: Download MongoDB GPG key
      shell: |
        curl -fsSL https://www.mongodb.org/static/pgp/server-4.4.asc | \
        gpg --dearmor -o /usr/share/keyrings/mongodb-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/mongodb-archive-keyring.gpg

    # Step 3: Add MongoDB repository for Raspberry Pi OS (ARM64)
    - name: Add MongoDB repository for Raspberry Pi OS (ARM64)
      copy:
        dest: /etc/apt/sources.list.d/mongodb-org-4.4.list
        content: |
          deb [signed-by=/usr/share/keyrings/mongodb-archive-keyring.gpg] https://repo.mongodb.org/apt/raspbian buster/mongodb-org/4.4 main
        mode: '0644'

    # Step 4: Update package list
    - name: Update package list
      apt:
        update_cache: yes

    # Step 5: Install MongoDB
    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present

    # Step 6: Ensure MongoDB service is started
    - name: Ensure MongoDB service is started
      systemd:
        name: mongod
        state: started
        enabled: yes

    # Step 7: Download UniFi Network Controller .deb package
    - name: Download UniFi Network Controller .deb package
      get_url:
        url: "https://dl.ui.com/unifi/5.13.29/unifi_sysvinit_all.deb"  # Replace with latest version URL
        dest: /tmp/unifi_sysvinit_all.deb
        mode: '0755'

    # Step 8: Install UniFi Network Controller .deb package using apt
    - name: Install UniFi Network Controller .deb package
      apt:
        deb: /tmp/unifi_sysvinit_all.deb
        state: present

    # Step 9: Ensure dependencies are resolved after installing UniFi .deb package
    - name: Ensure dependencies are resolved
      apt:
        name: "*"
        state: latest
        update_cache: yes

    # Step 10: Ensure UniFi Network Controller service is started
    - name: Ensure UniFi Network Controller service is started
      systemd:
        name: unifi
        state: started
        enabled: yes

    # Step 11: Open firewall for UniFi Network Controller (if using UFW)
    - name: Check if UFW is installed
      command: ufw status
      register: ufw_status
      ignore_errors: true

    - name: Open firewall for UniFi Network Control
