---
- name: Setup Home Assistant in Podman for dakboard user with auto-start on boot
  hosts: all
  become: true
  tasks:
    # Step 1: Ensure /etc/containers/registries.conf includes Docker Hub
    - name: Ensure /etc/containers/registries.conf includes Docker Hub
      lineinfile:
        path: /etc/containers/registries.conf
        line: 'unqualified-search-registries = ["docker.io"]'
        create: yes

    # Step 2: Check if Home Assistant container is already running
    - name: Check if Home Assistant container is running
      command: podman ps -q --filter name=home-assistant
      register: home_assistant_running
      changed_when: false
      failed_when: false

    # Step 3: Pull Home Assistant container image if it's not already present
    - name: Pull Home Assistant container image using Podman
      command: podman pull ghcr.io/home-assistant/home-assistant:stable
      when: home_assistant_running.stdout == ""

    # Step 4: Run Home Assistant container under dakboard user if not running
    - name: Run Home Assistant container under dakboard user
      command: >
        podman run -d --name home-assistant
        --privileged
        --restart=unless-stopped
        -e TZ=America/New_York
        -v /mnt/data/homeassistant:/config
        -v /run/dbus:/run/dbus:ro
        --network=host
        --workdir /home/dakboard
        ghcr.io/home-assistant/home-assistant:stable
      environment:
        HOME: /home/dakboard
      when: home_assistant_running.stdout == ""

    # Step 5: Add dakboard to Podman group if not already added
    - name: Add dakboard to Podman group
      user:
        name: dakboard
        group: podman
        append: yes

    # Step 6: Create a systemd service to start Home Assistant on boot
    - name: Create systemd service for Home Assistant container
      copy:
        dest: /etc/systemd/system/home-assistant.service
        content: |
          [Unit]
          Description=Home Assistant Container
          After=network.target

          [Service]
          ExecStart=/usr/bin/podman start home-assistant
          ExecStop=/usr/bin/podman stop home-assistant
          Restart=always
          User=dakboard
          RestartSec=5

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd

    # Step 7: Enable Home Assistant systemd service
    - name: Enable Home Assistant systemd service
      systemd:
        name: home-assistant.service
        enabled: true
        state: started

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes
