---
- name: Configure touchscreen support and display on/off scheduling
  hosts: all
  become: true
  tasks:

    - name: Ensure vcgencmd is available
      package:
        name: libraspberrypi-bin
        state: present

    - name: Create udev rule for touchscreen wake
      copy:
        dest: /etc/udev/rules.d/99-touchscreen.rules
        content: |
          ACTION=="add", SUBSYSTEM=="input", KERNEL=="event*", ATTRS{name}=="*touchscreen*", RUN+="/usr/bin/systemctl start turn_on_display_touch.service"

    - name: Create systemd service for display wake via touchscreen
      copy:
        dest: /etc/systemd/system/turn_on_display_touch.service
        content: |
          [Unit]
          Description=Turn on HDMI Display (Touch)

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/vcgencmd display_power 1

          [Install]
          WantedBy=multi-user.target
      notify: Reload systemd

    - name: Create all display timer/services
      block:
        - name: Create turn_on_display.service
          copy:
            dest: /etc/systemd/system/turn_on_display.service
            content: |
              [Unit]
              Description=Turn on HDMI Display

              [Service]
              Type=oneshot
              ExecStart=/usr/bin/vcgencmd display_power 1

        - name: Create turn_on_display.timer
          copy:
            dest: /etc/systemd/system/turn_on_display.timer
            content: |
              [Unit]
              Description=Turn on display at 05:30

              [Timer]
              OnCalendar=*-*-* 05:30:00
              Persistent=true

              [Install]
              WantedBy=timers.target

        - name: Create turn_off_display.service
          copy:
            dest: /etc/systemd/system/turn_off_display.service
            content: |
              [Unit]
              Description=Turn off HDMI Display

              [Service]
              Type=oneshot
              ExecStart=/usr/bin/vcgencmd display_power 0

        - name: Create turn_off_display.timer
          copy:
            dest: /etc/systemd/system/turn_off_display.timer
            content: |
              [Unit]
              Description=Turn off display at 09:00

              [Timer]
              OnCalendar=*-*-* 09:00:00
              Persistent=true

              [Install]
              WantedBy=timers.target

        - name: Create turn_on_display2.service
          copy:
            dest: /etc/systemd/system/turn_on_display2.service
            content: |
              [Unit]
              Description=Turn on HDMI Display (Afternoon)

              [Service]
              Type=oneshot
              ExecStart=/usr/bin/vcgencmd display_power 1

        - name: Create turn_on_display2.timer
          copy:
            dest: /etc/systemd/system/turn_on_display2.timer
            content: |
              [Unit]
              Description=Turn on display at 16:30

              [Timer]
              OnCalendar=*-*-* 16:30:00
              Persistent=true

              [Install]
              WantedBy=timers.target

        - name: Create turn_off_display2.service
          copy:
            dest: /etc/systemd/system/turn_off_display2.service
            content: |
              [Unit]
              Description=Turn off HDMI Display (Night)

              [Service]
              Type=oneshot
              ExecStart=/usr/bin/vcgencmd display_power 0

        - name: Create turn_off_display2.timer
          copy:
            dest: /etc/systemd/system/turn_off_display2.timer
            content: |
              [Unit]
              Description=Turn off display at 21:00

              [Timer]
              OnCalendar=*-*-* 21:00:00
              Persistent=true

              [Install]
              WantedBy=timers.target
      notify: Reload systemd

    - name: Enable display timers
      systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - turn_on_display.timer
        - turn_off_display.timer
        - turn_on_display2.timer
        - turn_off_display2.timer

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reexec && systemctl daemon-reload
