---
- name: Install k3s server
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" sh -
  args:
    creates: /etc/systemd/system/k3s.service

- name: Wait for k3s to be ready
  wait_for:
    port: 6443
    host: "{{ ansible_host }}"
    delay: 10

- name: Get k3s token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token_raw

- name: Set k3s token fact
  set_fact:
    k3s_token: "{{ k3s_token_raw['content'] | b64decode | trim }}"

- name: Share k3s token with other hosts
  add_host:
    name: "{{ item }}"
    k3s_token: "{{ k3s_token }}"
  loop: "{{ groups['all'] }}"
  when: k3s_token is defined
