---
- name: Check if Docker is already installed
  command: docker --version
  register: docker_check
  ignore_errors: true
  changed_when: false

- name: Install Docker on Debian-based systems
  shell: curl -fsSL https://get.docker.com | sh
  when: ansible_facts['os_family'] == "Debian"

- name: Install Docker on Fedora
  become: true
  dnf:
    name:
      - docker
      - docker-compose
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Install Docker on Arch
  become: true
  pacman:
    name: docker
    state: present
  when: ansible_facts['distribution'] == "Archlinux"

- name: Enable and start Docker
  become: true
  systemd:
    name: docker
    enabled: true
    state: started

- name: Install Docker prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  when: docker_check.rc != 0

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: docker_check.rc != 0

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
  when: docker_check.rc != 0

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes
  when: docker_check.rc != 0

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  when: docker_check.rc != 0

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Verify Docker installation
  command: docker run --rm hello-world
  register: docker_test
  become_user: "{{ ansible_user }}"
  when: docker_check.rc != 0

- name: Display Docker version
  debug:
    msg: "Docker successfully installed: {{ docker_test.stdout_lines[-1] if docker_check.rc != 0 else 'Docker was already installed' }}"
