---
# roles/plex/tasks/main.yml

- name: Pull Plex Media Server image (linuxserver)
  docker_image:
    name: "lscr.io/linuxserver/plex:{{ plex_version | default('latest') }}"
    source: pull

- name: Get current user UID
  command: id -u
  register: plex_uid
  changed_when: false

- name: Get current user GID
  command: id -g
  register: plex_gid
  changed_when: false

- name: Create Plex config directory
  file:
    path: "{{ plex_config_dir | default('/opt/plex/config') }}"
    state: directory
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"
    mode: '0755'

- name: Create Plex media directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"
    mode: '0755'
  loop:
    - "{{ plex_movies_dir | default('/opt/plex/movies') }}"
    - "{{ plex_tv_dir | default('/opt/plex/tv') }}"
    - "{{ plex_music_dir | default('/opt/plex/music') }}"

- name: Check if Plex container exists
  docker_container_info:
    name: plex
  register: plex_container_info

- name: Remove existing Plex container if force recreate
  docker_container:
    name: plex
    state: absent
  when:
    - plex_container_info.exists
    - force_recreate | default(false) | bool

- name: Run Plex Media Server container (linuxserver)
  docker_container:
    name: plex
    image: "lscr.io/linuxserver/plex:{{ plex_version | default('latest') }}"
    restart_policy: unless-stopped
    recreate: "{{ force_recreate | default(false) }}"
    network_mode: host
    volumes:
      - "{{ plex_config_dir | default('/opt/plex/config') }}:/config"
      - "{{ plex_movies_dir | default('/opt/plex/movies') }}:/movies"
      - "{{ plex_tv_dir | default('/opt/plex/tv') }}:/tv"
      - "{{ plex_music_dir | default('/opt/plex/music') }}:/music"
    env:
      TZ: "{{ timezone | default('UTC') }}"
      PUID: "{{ plex_uid.stdout }}"
      PGID: "{{ plex_gid.stdout }}"
      VERSION: docker

- name: Wait for Plex to start
  wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: 32400
    delay: 15
    timeout: 120
  register: plex_startup

- name: Display Plex startup result
  debug:
    msg: |
      {% if plex_startup.failed %}
      ⚠️  Plex may be starting up - check logs with: docker logs plex
      {% else %}
      ✅ Plex Media Server is running at: http://{{ ansible_default_ipv4.address }}:32400/web
      {% endif %}

- name: Show Plex setup info
  debug:
    msg: |
      📋 Plex Media Server Setup:
      1. Visit: http://{{ ansible_default_ipv4.address }}:32400/web
      2. Sign in with your Plex account
      3. Add media libraries:
         - Movies: /movies
         - TV: /tv
         - Music: /music
      
      📁 Configuration: {{ plex_config_dir | default('/opt/plex/config') }}
      📁 Media directories:
         - Movies: {{ plex_movies_dir | default('/opt/plex/movies') }}
         - TV: {{ plex_tv_dir | default('/opt/plex/tv') }}
         - Music: {{ plex_music_dir | default('/opt/plex/music') }}
  when: not plex_container_info.exists or (force_recreate | default(false) | bool)
