---
- name: Deploy Homeassistant to Kubernetes
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition: "{{ lookup('template', 'deployment.yaml.j2') | from_yaml_all | list }}"
